/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashSchemaRequest {
    #[serde(rename = "schema")]
    pub schema: String,
}

impl HashSchemaRequest {
    pub fn new(schema: String) -> HashSchemaRequest {
        HashSchemaRequest {
            schema,
        }
    }
}

