/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshLatestConcreteConfigRequest {
    /// The config schema digest
    #[serde(rename = "config_schema_digest")]
    pub config_schema_digest: String,
    /// The config slug
    #[serde(rename = "config_slug")]
    pub config_slug: String,
}

impl RefreshLatestConcreteConfigRequest {
    pub fn new(
        config_schema_digest: String,
        config_slug: String,
    ) -> RefreshLatestConcreteConfigRequest {
        RefreshLatestConcreteConfigRequest {
            config_schema_digest,
            config_slug,
        }
    }
}
