/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateDeviceRequest {
    /// The public key in PEM format
    #[serde(rename = "public_key_pem")]
    pub public_key_pem: String,
}

impl ActivateDeviceRequest {
    pub fn new(public_key_pem: String) -> ActivateDeviceRequest {
        ActivateDeviceRequest { public_key_pem }
    }
}
