/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseConfigSchema {
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the config schema
    #[serde(rename = "id")]
    pub id: String,
    /// Config schema version for the config type
    #[serde(rename = "version")]
    pub version: i32,
    /// Hash of the config schema contents
    #[serde(rename = "digest")]
    pub digest: String,
    /// The file path to deploy the config instance relative to `/srv/miru/config_instances`. `v1/motion-control.json` would deploy to `/srv/miru/config_instances/v1/motion-control.json`
    #[serde(rename = "relative_filepath")]
    pub relative_filepath: String,
    /// Timestamp of when the config schema was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the config schema was last updated
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// ID of the config type
    #[serde(rename = "config_type_id")]
    pub config_type_id: String,
    /// The config schema's JSON Schema definition
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<serde_json::Value>,
}

impl BaseConfigSchema {
    pub fn new(
        object: Object,
        id: String,
        version: i32,
        digest: String,
        relative_filepath: String,
        created_at: String,
        updated_at: String,
        config_type_id: String,
        content: Option<serde_json::Value>,
    ) -> BaseConfigSchema {
        BaseConfigSchema {
            object,
            id,
            version,
            digest,
            relative_filepath,
            created_at,
            updated_at,
            config_type_id,
            content,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "config_schema")]
    ConfigSchema,
}

impl Default for Object {
    fn default() -> Object {
        Self::ConfigSchema
    }
}
