/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BillingPlan {
    #[serde(rename = "hobby")]
    BILLING_PLAN_HOBBY,
    #[serde(rename = "startup")]
    BILLING_PLAN_STARTUP,
    #[serde(rename = "enterprise")]
    BILLING_PLAN_ENTERPRISE,
}

impl std::fmt::Display for BillingPlan {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BILLING_PLAN_HOBBY => write!(f, "hobby"),
            Self::BILLING_PLAN_STARTUP => write!(f, "startup"),
            Self::BILLING_PLAN_ENTERPRISE => write!(f, "enterprise"),
        }
    }
}

impl Default for BillingPlan {
    fn default() -> BillingPlan {
        Self::BILLING_PLAN_HOBBY
    }
}
