/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigSchemaExpand {
    #[serde(rename = "created_by")]
    CONFIG_SCHEMA_EXPAND_CREATED_BY,
    #[serde(rename = "updated_by")]
    CONFIG_SCHEMA_EXPAND_UPDATED_BY,
    #[serde(rename = "content")]
    CONFIG_SCHEMA_EXPAND_CONTENT,
    #[serde(rename = "config_type")]
    CONFIG_SCHEMA_EXPAND_CONFIG_TYPE,
    #[serde(rename = "config_schema_git_commits")]
    CONFIG_SCHEMA_EXPAND_CONFIG_SCHEMA_GIT_COMMITS,
    #[serde(rename = "overrides")]
    CONFIG_SCHEMA_EXPAND_OVERRIDES,
}

impl std::fmt::Display for ConfigSchemaExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_SCHEMA_EXPAND_CREATED_BY => write!(f, "created_by"),
            Self::CONFIG_SCHEMA_EXPAND_UPDATED_BY => write!(f, "updated_by"),
            Self::CONFIG_SCHEMA_EXPAND_CONTENT => write!(f, "content"),
            Self::CONFIG_SCHEMA_EXPAND_CONFIG_TYPE => write!(f, "config_type"),
            Self::CONFIG_SCHEMA_EXPAND_CONFIG_SCHEMA_GIT_COMMITS => {
                write!(f, "config_schema_git_commits")
            }
            Self::CONFIG_SCHEMA_EXPAND_OVERRIDES => write!(f, "overrides"),
        }
    }
}

impl Default for ConfigSchemaExpand {
    fn default() -> ConfigSchemaExpand {
        Self::CONFIG_SCHEMA_EXPAND_CREATED_BY
    }
}
