/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigInstanceStatus {
    #[serde(rename = "created")]
    CONFIG_INSTANCE_STATUS_CREATED,
    #[serde(rename = "queued")]
    CONFIG_INSTANCE_STATUS_QUEUED,
    #[serde(rename = "deployed")]
    CONFIG_INSTANCE_STATUS_DEPLOYED,
    #[serde(rename = "removed")]
    CONFIG_INSTANCE_STATUS_REMOVED,
    #[serde(rename = "failed")]
    CONFIG_INSTANCE_STATUS_FAILED,
}

impl std::fmt::Display for ConfigInstanceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_INSTANCE_STATUS_CREATED => write!(f, "created"),
            Self::CONFIG_INSTANCE_STATUS_QUEUED => write!(f, "queued"),
            Self::CONFIG_INSTANCE_STATUS_DEPLOYED => write!(f, "deployed"),
            Self::CONFIG_INSTANCE_STATUS_REMOVED => write!(f, "removed"),
            Self::CONFIG_INSTANCE_STATUS_FAILED => write!(f, "failed"),
        }
    }
}

impl Default for ConfigInstanceStatus {
    fn default() -> ConfigInstanceStatus {
        Self::CONFIG_INSTANCE_STATUS_CREATED
    }
}
