/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigInstanceExpand {
    #[serde(rename = "created_by")]
    CONFIG_INSTANCE_EXPAND_CREATED_BY,
    #[serde(rename = "updated_by")]
    CONFIG_INSTANCE_EXPAND_UPDATED_BY,
    #[serde(rename = "content")]
    CONFIG_INSTANCE_EXPAND_CONTENT,
    #[serde(rename = "patch")]
    CONFIG_INSTANCE_EXPAND_PATCH,
    #[serde(rename = "config_schema")]
    CONFIG_INSTANCE_EXPAND_CONFIG_SCHEMA,
    #[serde(rename = "device")]
    CONFIG_INSTANCE_EXPAND_DEVICE,
    #[serde(rename = "config_type")]
    CONFIG_INSTANCE_EXPAND_CONFIG_TYPE,
    #[serde(rename = "validation")]
    CONFIG_INSTANCE_EXPAND_VALIDATION,
}

impl std::fmt::Display for ConfigInstanceExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_INSTANCE_EXPAND_CREATED_BY => write!(f, "created_by"),
            Self::CONFIG_INSTANCE_EXPAND_UPDATED_BY => write!(f, "updated_by"),
            Self::CONFIG_INSTANCE_EXPAND_CONTENT => write!(f, "content"),
            Self::CONFIG_INSTANCE_EXPAND_PATCH => write!(f, "patch"),
            Self::CONFIG_INSTANCE_EXPAND_CONFIG_SCHEMA => write!(f, "config_schema"),
            Self::CONFIG_INSTANCE_EXPAND_DEVICE => write!(f, "device"),
            Self::CONFIG_INSTANCE_EXPAND_CONFIG_TYPE => write!(f, "config_type"),
            Self::CONFIG_INSTANCE_EXPAND_VALIDATION => write!(f, "validation"),
        }
    }
}

impl Default for ConfigInstanceExpand {
    fn default() -> ConfigInstanceExpand {
        Self::CONFIG_INSTANCE_EXPAND_CREATED_BY
    }
}
