/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigSchemaGitCommit {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "file_path")]
    pub file_path: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "git_commit_id")]
    pub git_commit_id: String,
    #[serde(rename = "config_schema_id")]
    pub config_schema_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "created_by_id")]
    pub created_by_id: String,
    #[serde(rename = "created_by", deserialize_with = "Option::deserialize")]
    pub created_by: Option<Box<models::Principal>>,
    #[serde(rename = "git_commit", deserialize_with = "Option::deserialize")]
    pub git_commit: Option<Box<models::GitCommit>>,
    #[serde(rename = "config_schema", deserialize_with = "Option::deserialize")]
    pub config_schema: Option<Box<models::ConfigSchema>>,
}

impl ConfigSchemaGitCommit {
    pub fn new(
        object: Object,
        id: String,
        file_path: String,
        url: String,
        git_commit_id: String,
        config_schema_id: String,
        created_at: String,
        created_by_id: String,
        created_by: Option<models::Principal>,
        git_commit: Option<models::GitCommit>,
        config_schema: Option<models::ConfigSchema>,
    ) -> ConfigSchemaGitCommit {
        ConfigSchemaGitCommit {
            object,
            id,
            file_path,
            url,
            git_commit_id,
            config_schema_id,
            created_at,
            created_by_id,
            created_by: created_by.map(Box::new),
            git_commit: git_commit.map(Box::new),
            config_schema: config_schema.map(Box::new),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "config_schema_git_commit")]
    ConfigSchemaGitCommit,
}

impl Default for Object {
    fn default() -> Object {
        Self::ConfigSchemaGitCommit
    }
}
