/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigType {
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the config type
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the config type
    #[serde(rename = "name")]
    pub name: String,
    /// An immutable, code-friendly name for the config type
    #[serde(rename = "slug")]
    pub slug: String,
    /// Timestamp of when the config type was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the config type was last updated
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// Whether this config type requires custom validation for its config instances
    #[serde(rename = "custom_validation_enabled")]
    pub custom_validation_enabled: bool,
    #[serde(rename = "created_by_id")]
    pub created_by_id: String,
    #[serde(rename = "updated_by_id")]
    pub updated_by_id: String,
    #[serde(rename = "created_by", deserialize_with = "Option::deserialize")]
    pub created_by: Option<Box<models::Principal>>,
    #[serde(rename = "updated_by", deserialize_with = "Option::deserialize")]
    pub updated_by: Option<Box<models::Principal>>,
    /// Expand the config schemas using 'expand[]=config_schemas' in the query string
    #[serde(rename = "config_schemas", deserialize_with = "Option::deserialize")]
    pub config_schemas: Option<Box<models::ConfigSchemaList>>,
}

impl ConfigType {
    pub fn new(
        object: Object,
        id: String,
        name: String,
        slug: String,
        created_at: String,
        updated_at: String,
        custom_validation_enabled: bool,
        created_by_id: String,
        updated_by_id: String,
        created_by: Option<models::Principal>,
        updated_by: Option<models::Principal>,
        config_schemas: Option<models::ConfigSchemaList>,
    ) -> ConfigType {
        ConfigType {
            object,
            id,
            name,
            slug,
            created_at,
            updated_at,
            custom_validation_enabled,
            created_by_id,
            updated_by_id,
            created_by: created_by.map(Box::new),
            updated_by: updated_by.map(Box::new),
            config_schemas: config_schemas.map(Box::new),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "config_type")]
    ConfigType,
}

impl Default for Object {
    fn default() -> Object {
        Self::ConfigType
    }
}
