/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ConfigInstanceValidationError : The validation error for a specific parameter in the config instance
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigInstanceValidationError {
    #[serde(rename = "parameter_path")]
    pub parameter_path: Vec<String>,
    #[serde(rename = "message")]
    pub message: String,
}

impl ConfigInstanceValidationError {
    /// The validation error for a specific parameter in the config instance
    pub fn new(parameter_path: Vec<String>, message: String) -> ConfigInstanceValidationError {
        ConfigInstanceValidationError {
            parameter_path,
            message,
        }
    }
}
