/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigInstanceOrderBy {
    #[serde(rename = "id")]
    CONFIG_INSTANCE_ORDER_BY_ID,
    #[serde(rename = "created_at")]
    CONFIG_INSTANCE_ORDER_BY_CREATED_AT,
    #[serde(rename = "target_status")]
    CONFIG_INSTANCE_ORDER_BY_TARGET_STATUS,
    #[serde(rename = "activity_status")]
    CONFIG_INSTANCE_ORDER_BY_ACTIVITY_STATUS,
    #[serde(rename = "error_status")]
    CONFIG_INSTANCE_ORDER_BY_ERROR_STATUS,
    #[serde(rename = "config_type_id")]
    CONFIG_INSTANCE_ORDER_BY_CONFIG_TYPE_ID,
    #[serde(rename = "config_schema_id")]
    CONFIG_INSTANCE_ORDER_BY_CONFIG_SCHEMA_ID,
    #[serde(rename = "device_id")]
    CONFIG_INSTANCE_ORDER_BY_DEVICE_ID,
}

impl std::fmt::Display for ConfigInstanceOrderBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_INSTANCE_ORDER_BY_ID => write!(f, "id"),
            Self::CONFIG_INSTANCE_ORDER_BY_CREATED_AT => write!(f, "created_at"),
            Self::CONFIG_INSTANCE_ORDER_BY_TARGET_STATUS => write!(f, "target_status"),
            Self::CONFIG_INSTANCE_ORDER_BY_ACTIVITY_STATUS => write!(f, "activity_status"),
            Self::CONFIG_INSTANCE_ORDER_BY_ERROR_STATUS => write!(f, "error_status"),
            Self::CONFIG_INSTANCE_ORDER_BY_CONFIG_TYPE_ID => write!(f, "config_type_id"),
            Self::CONFIG_INSTANCE_ORDER_BY_CONFIG_SCHEMA_ID => write!(f, "config_schema_id"),
            Self::CONFIG_INSTANCE_ORDER_BY_DEVICE_ID => write!(f, "device_id"),
        }
    }
}

impl Default for ConfigInstanceOrderBy {
    fn default() -> ConfigInstanceOrderBy {
        Self::CONFIG_INSTANCE_ORDER_BY_ID
    }
}
