/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceTagPaginatedList {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "total_count")]
    pub total_count: i64,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "data")]
    pub data: Vec<models::DeviceTag>,
}

impl DeviceTagPaginatedList {
    pub fn new(
        object: Object,
        total_count: i64,
        limit: i32,
        offset: i32,
        has_more: bool,
        data: Vec<models::DeviceTag>,
    ) -> DeviceTagPaginatedList {
        DeviceTagPaginatedList {
            object,
            total_count,
            limit,
            offset,
            has_more,
            data,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "list")]
    List,
}

impl Default for Object {
    fn default() -> Object {
        Self::List
    }
}
