/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DeviceStatus : The status of the device - Inactive: The miru agent has not yet been installed / authenticated - Staged: The device has been staged for activation - Activated: The miru agent has been installed and authenticated
/// The status of the device - Inactive: The miru agent has not yet been installed / authenticated - Staged: The device has been staged for activation - Activated: The miru agent has been installed and authenticated
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceStatus {
    #[serde(rename = "inactive")]
    DEVICE_STATUS_INACTIVE,
    #[serde(rename = "staged")]
    DEVICE_STATUS_STAGED,
    #[serde(rename = "activated")]
    DEVICE_STATUS_ACTIVATED,
}

impl std::fmt::Display for DeviceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEVICE_STATUS_INACTIVE => write!(f, "inactive"),
            Self::DEVICE_STATUS_STAGED => write!(f, "staged"),
            Self::DEVICE_STATUS_ACTIVATED => write!(f, "activated"),
        }
    }
}

impl Default for DeviceStatus {
    fn default() -> DeviceStatus {
        Self::DEVICE_STATUS_INACTIVE
    }
}
