/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Override {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "hierarchy_position")]
    pub hierarchy_position: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "created_by_id")]
    pub created_by_id: String,
    #[serde(rename = "updated_by_id")]
    pub updated_by_id: String,
    #[serde(rename = "config_schema_id")]
    pub config_schema_id: String,
    #[serde(rename = "created_by", deserialize_with = "Option::deserialize")]
    pub created_by: Option<Box<models::Principal>>,
    #[serde(rename = "updated_by", deserialize_with = "Option::deserialize")]
    pub updated_by: Option<Box<models::Principal>>,
    #[serde(rename = "key_value_pairs", deserialize_with = "Option::deserialize")]
    pub key_value_pairs: Option<Box<models::OverrideKeyValuePairList>>,
    #[serde(rename = "config_schema", deserialize_with = "Option::deserialize")]
    pub config_schema: Option<Box<models::ConfigSchema>>,
}

impl Override {
    pub fn new(
        object: Object,
        id: String,
        name: String,
        hierarchy_position: i32,
        created_at: String,
        updated_at: String,
        created_by_id: String,
        updated_by_id: String,
        config_schema_id: String,
        created_by: Option<models::Principal>,
        updated_by: Option<models::Principal>,
        key_value_pairs: Option<models::OverrideKeyValuePairList>,
        config_schema: Option<models::ConfigSchema>,
    ) -> Override {
        Override {
            object,
            id,
            name,
            hierarchy_position,
            created_at,
            updated_at,
            created_by_id,
            updated_by_id,
            config_schema_id,
            created_by: created_by.map(Box::new),
            updated_by: updated_by.map(Box::new),
            key_value_pairs: key_value_pairs.map(Box::new),
            config_schema: config_schema.map(Box::new),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "override")]
    Override,
}

impl Default for Object {
    fn default() -> Object {
        Self::Override
    }
}
