/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pong {
    #[serde(rename = "message_id")]
    pub message_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl Pong {
    pub fn new(message_id: String, timestamp: String) -> Pong {
        Pong {
            message_id,
            timestamp,
        }
    }
}
