/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Scope {
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the scope
    #[serde(rename = "slug")]
    pub slug: String,
    /// Description of the scope
    #[serde(rename = "description")]
    pub description: String,
}

impl Scope {
    pub fn new(object: Object, slug: String, description: String) -> Scope {
        Scope {
            object,
            slug,
            description,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "scope")]
    Scope,
}

impl Default for Object {
    fn default() -> Object {
        Self::Scope
    }
}
