/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncDevice {
    #[serde(rename = "is_synced")]
    pub is_synced: bool,
}

impl SyncDevice {
    pub fn new(is_synced: bool) -> SyncDevice {
        SyncDevice { is_synced }
    }
}
