/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "created_by_id")]
    pub created_by_id: String,
    #[serde(rename = "updated_by_id")]
    pub updated_by_id: String,
    #[serde(rename = "tag_type_id")]
    pub tag_type_id: String,
    #[serde(rename = "created_by", deserialize_with = "Option::deserialize")]
    pub created_by: Option<Box<models::Principal>>,
    #[serde(rename = "updated_by", deserialize_with = "Option::deserialize")]
    pub updated_by: Option<Box<models::Principal>>,
    #[serde(rename = "tag_type", deserialize_with = "Option::deserialize")]
    pub tag_type: Option<Box<models::TagType>>,
    #[serde(rename = "metadata", deserialize_with = "Option::deserialize")]
    pub metadata: Option<serde_json::Value>,
}

impl Tag {
    pub fn new(
        object: Object,
        id: String,
        name: String,
        created_at: String,
        updated_at: String,
        created_by_id: String,
        updated_by_id: String,
        tag_type_id: String,
        created_by: Option<models::Principal>,
        updated_by: Option<models::Principal>,
        tag_type: Option<models::TagType>,
        metadata: Option<serde_json::Value>,
    ) -> Tag {
        Tag {
            object,
            id,
            name,
            created_at,
            updated_at,
            created_by_id,
            updated_by_id,
            tag_type_id,
            created_by: created_by.map(Box::new),
            updated_by: updated_by.map(Box::new),
            tag_type: tag_type.map(Box::new),
            metadata,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "tag")]
    Tag,
}

impl Default for Object {
    fn default() -> Object {
        Self::Tag
    }
}
