/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDeviceFromAgentRequest {
    /// The version of the agent the device is running
    #[serde(rename = "agent_version", skip_serializing_if = "Option::is_none")]
    pub agent_version: Option<String>,
}

impl UpdateDeviceFromAgentRequest {
    pub fn new() -> UpdateDeviceFromAgentRequest {
        UpdateDeviceFromAgentRequest {
            agent_version: None,
        }
    }
}
