/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateConfigInstanceRequest {
    #[serde(rename = "activity_status", deserialize_with = "Option::deserialize")]
    pub activity_status: Option<models::ConfigInstanceActivityStatus>,
    #[serde(rename = "error_status", deserialize_with = "Option::deserialize")]
    pub error_status: Option<models::ConfigInstanceErrorStatus>,
}

impl UpdateConfigInstanceRequest {
    pub fn new(
        activity_status: Option<models::ConfigInstanceActivityStatus>,
        error_status: Option<models::ConfigInstanceErrorStatus>,
    ) -> UpdateConfigInstanceRequest {
        UpdateConfigInstanceRequest {
            activity_status,
            error_status,
        }
    }
}
