/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigInstanceContent {
    /// The configuration values associated with the config instance
    #[serde(rename = "content")]
    pub content: serde_json::Value,
}

impl ConfigInstanceContent {
    pub fn new(content: serde_json::Value) -> ConfigInstanceContent {
        ConfigInstanceContent { content }
    }
}
