/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshLatestConfigInstanceRequest {
    /// The config schema digest
    #[serde(rename = "config_schema_digest")]
    pub config_schema_digest: String,
    /// The config type slug
    #[serde(rename = "config_type_slug")]
    pub config_type_slug: String,
}

impl RefreshLatestConfigInstanceRequest {
    pub fn new(
        config_schema_digest: String,
        config_type_slug: String,
    ) -> RefreshLatestConfigInstanceRequest {
        RefreshLatestConfigInstanceRequest {
            config_schema_digest,
            config_type_slug,
        }
    }
}
