/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateClientRequest {
    /// The public key in PEM format
    #[serde(rename = "public_key_pem")]
    pub public_key_pem: String,
}

impl ActivateClientRequest {
    pub fn new(public_key_pem: String) -> ActivateClientRequest {
        ActivateClientRequest {
            public_key_pem,
        }
    }
}

