/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArtifactSourceType {
    #[serde(rename = "github")]
    Github,
    #[serde(rename = "registry")]
    Registry,
}

impl std::fmt::Display for ArtifactSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Github => write!(f, "github"),
            Self::Registry => write!(f, "registry"),
        }
    }
}

impl Default for ArtifactSourceType {
    fn default() -> ArtifactSourceType {
        Self::Github
    }
}
