/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendConcreteConfig {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "config_schema_id")]
    pub config_schema_id: String,
    #[serde(rename = "concrete_config", deserialize_with = "Option::deserialize")]
    pub concrete_config: Option<serde_json::Value>,
}

impl BackendConcreteConfig {
    pub fn new(object: Object, id: String, created_at: String, client_id: String, config_schema_id: String, concrete_config: Option<serde_json::Value>) -> BackendConcreteConfig {
        BackendConcreteConfig {
            object,
            id,
            created_at,
            client_id,
            config_schema_id,
            concrete_config,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "concrete_config")]
    ConcreteConfig,
}

impl Default for Object {
    fn default() -> Object {
        Self::ConcreteConfig
    }
}

