/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildStep {
    #[serde(rename = "step", deserialize_with = "Option::deserialize")]
    pub step: Option<i32>,
    #[serde(rename = "log_entries", skip_serializing_if = "Option::is_none")]
    pub log_entries: Option<Vec<models::LogEntry>>,
}

impl BuildStep {
    pub fn new(step: Option<i32>) -> BuildStep {
        BuildStep {
            step,
            log_entries: None,
        }
    }
}
