/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientTagsRequest {
    #[serde(rename = "client_tags")]
    pub client_tags: Vec<models::ClientTagRequestItem>,
}

impl ClientTagsRequest {
    pub fn new(client_tags: Vec<models::ClientTagRequestItem>) -> ClientTagsRequest {
        ClientTagsRequest {
            client_tags,
        }
    }
}

