/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientExpand {
    #[serde(rename = "created_by")]
    CLIENT_EXPAND_CREATED_BY,
    #[serde(rename = "updated_by")]
    CLIENT_EXPAND_UPDATED_BY,
    #[serde(rename = "client_tags")]
    CLIENT_EXPAND_CLIENT_TAGS,
}

impl std::fmt::Display for ClientExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CLIENT_EXPAND_CREATED_BY => write!(f, "created_by"),
            Self::CLIENT_EXPAND_UPDATED_BY => write!(f, "updated_by"),
            Self::CLIENT_EXPAND_CLIENT_TAGS => write!(f, "client_tags"),
        }
    }
}

impl Default for ClientExpand {
    fn default() -> ClientExpand {
        Self::CLIENT_EXPAND_CREATED_BY
    }
}
