/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Client {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "created_by_id", deserialize_with = "Option::deserialize")]
    pub created_by_id: Option<String>,
    #[serde(rename = "updated_by_id", deserialize_with = "Option::deserialize")]
    pub updated_by_id: Option<String>,
    #[serde(rename = "created_by", deserialize_with = "Option::deserialize")]
    pub created_by: Option<Box<models::User>>,
    #[serde(rename = "updated_by", deserialize_with = "Option::deserialize")]
    pub updated_by: Option<Box<models::User>>,
    #[serde(rename = "client_tags", deserialize_with = "Option::deserialize")]
    pub client_tags: Option<Box<models::ClientTagPaginatedList>>,
}

impl Client {
    pub fn new(
        object: Object,
        id: String,
        name: String,
        created_at: String,
        updated_at: String,
        created_by_id: Option<String>,
        updated_by_id: Option<String>,
        created_by: Option<models::User>,
        updated_by: Option<models::User>,
        client_tags: Option<models::ClientTagPaginatedList>,
    ) -> Client {
        Client {
            object,
            id,
            name,
            created_at,
            updated_at,
            created_by_id,
            updated_by_id,
            created_by: created_by.map(Box::new),
            updated_by: updated_by.map(Box::new),
            client_tags: client_tags.map(Box::new),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "client")]
    Client,
}

impl Default for Object {
    fn default() -> Object {
        Self::Client
    }
}
