/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientSearch {
    #[serde(rename = "name")]
    CLIENT_SEARCH_NAME,
    #[serde(rename = "tag")]
    CLIENT_SEARCH_TAG,
}

impl std::fmt::Display for ClientSearch {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CLIENT_SEARCH_NAME => write!(f, "name"),
            Self::CLIENT_SEARCH_TAG => write!(f, "tag"),
        }
    }
}

impl Default for ClientSearch {
    fn default() -> ClientSearch {
        Self::CLIENT_SEARCH_NAME
    }
}
