/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientTagRequestItem {
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "tag_id")]
    pub tag_id: String,
}

impl ClientTagRequestItem {
    pub fn new(client_id: String, tag_id: String) -> ClientTagRequestItem {
        ClientTagRequestItem { client_id, tag_id }
    }
}
