/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientOrderBy {
    #[serde(rename = "id")]
    CLIENT_ORDER_BY_ID,
    #[serde(rename = "created_at")]
    CLIENT_ORDER_BY_CREATED_AT,
    #[serde(rename = "updated_at")]
    CLIENT_ORDER_BY_UPDATED_AT,
    #[serde(rename = "name")]
    CLIENT_ORDER_BY_NAME,

}

impl std::fmt::Display for ClientOrderBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CLIENT_ORDER_BY_ID => write!(f, "id"),
            Self::CLIENT_ORDER_BY_CREATED_AT => write!(f, "created_at"),
            Self::CLIENT_ORDER_BY_UPDATED_AT => write!(f, "updated_at"),
            Self::CLIENT_ORDER_BY_NAME => write!(f, "name"),
        }
    }
}

impl Default for ClientOrderBy {
    fn default() -> ClientOrderBy {
        Self::CLIENT_ORDER_BY_ID
    }
}

