/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeFileVerificationRequest {
    #[serde(rename = "compose_file")]
    pub compose_file: String,
    #[serde(rename = "architecture")]
    pub architecture: String,
}

impl ComposeFileVerificationRequest {
    pub fn new(compose_file: String, architecture: String) -> ComposeFileVerificationRequest {
        ComposeFileVerificationRequest {
            compose_file,
            architecture,
        }
    }
}

