/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeFile {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "content")]
    pub content: String,
}

impl ComposeFile {
    pub fn new(object: Object, content: String) -> ComposeFile {
        ComposeFile { object, content }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "compose_file")]
    ComposeFile,
}

impl Default for Object {
    fn default() -> Object {
        Self::ComposeFile
    }
}
