/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConcreteConfigExpand {
    #[serde(rename = "client")]
    CONCRETE_CONFIG_EXPAND_CLIENT,
    #[serde(rename = "config_schema")]
    CONCRETE_CONFIG_EXPAND_CONFIG_SCHEMA,
    #[serde(rename = "concrete_config")]
    CONCRETE_CONFIG_EXPAND_CONCRETE_CONFIG,

}

impl std::fmt::Display for ConcreteConfigExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONCRETE_CONFIG_EXPAND_CLIENT => write!(f, "client"),
            Self::CONCRETE_CONFIG_EXPAND_CONFIG_SCHEMA => write!(f, "config_schema"),
            Self::CONCRETE_CONFIG_EXPAND_CONCRETE_CONFIG => write!(f, "concrete_config"),
        }
    }
}

impl Default for ConcreteConfigExpand {
    fn default() -> ConcreteConfigExpand {
        Self::CONCRETE_CONFIG_EXPAND_CLIENT
    }
}

