/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigSchemaSearch {
    #[serde(rename = "version")]
    CONFIG_SCHEMA_SEARCH_VERSION,
    #[serde(rename = "config")]
    CONFIG_SCHEMA_SEARCH_CONFIG,
    #[serde(rename = "commit_sha")]
    CONFIG_SCHEMA_SEARCH_COMMIT_SHA,
    #[serde(rename = "repository_name")]
    CONFIG_SCHEMA_SEARCH_REPOSITORY_NAME,
    #[serde(rename = "branch")]
    CONFIG_SCHEMA_SEARCH_BRANCH,

}

impl std::fmt::Display for ConfigSchemaSearch {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_SCHEMA_SEARCH_VERSION => write!(f, "version"),
            Self::CONFIG_SCHEMA_SEARCH_CONFIG => write!(f, "config"),
            Self::CONFIG_SCHEMA_SEARCH_COMMIT_SHA => write!(f, "commit_sha"),
            Self::CONFIG_SCHEMA_SEARCH_REPOSITORY_NAME => write!(f, "repository_name"),
            Self::CONFIG_SCHEMA_SEARCH_BRANCH => write!(f, "branch"),
        }
    }
}

impl Default for ConfigSchemaSearch {
    fn default() -> ConfigSchemaSearch {
        Self::CONFIG_SCHEMA_SEARCH_VERSION
    }
}

