/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigSchemaOrderBy {
    #[serde(rename = "id")]
    CONFIG_SCHEMA_ORDER_BY_ID,
    #[serde(rename = "created_at")]
    CONFIG_SCHEMA_ORDER_BY_CREATED_AT,
    #[serde(rename = "version")]
    CONFIG_SCHEMA_ORDER_BY_VERSION,

}

impl std::fmt::Display for ConfigSchemaOrderBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_SCHEMA_ORDER_BY_ID => write!(f, "id"),
            Self::CONFIG_SCHEMA_ORDER_BY_CREATED_AT => write!(f, "created_at"),
            Self::CONFIG_SCHEMA_ORDER_BY_VERSION => write!(f, "version"),
        }
    }
}

impl Default for ConfigSchemaOrderBy {
    fn default() -> ConfigSchemaOrderBy {
        Self::CONFIG_SCHEMA_ORDER_BY_ID
    }
}

