/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigExpand {
    #[serde(rename = "created_by")]
    CONFIG_EXPAND_CREATED_BY,
    #[serde(rename = "updated_by")]
    CONFIG_EXPAND_UPDATED_BY,
    #[serde(rename = "schemas")]
    CONFIG_EXPAND_SCHEMAS,

}

impl std::fmt::Display for ConfigExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_EXPAND_CREATED_BY => write!(f, "created_by"),
            Self::CONFIG_EXPAND_UPDATED_BY => write!(f, "updated_by"),
            Self::CONFIG_EXPAND_SCHEMAS => write!(f, "schemas"),
        }
    }
}

impl Default for ConfigExpand {
    fn default() -> ConfigExpand {
        Self::CONFIG_EXPAND_CREATED_BY
    }
}

