/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigSearch {
    #[serde(rename = "name")]
    CONFIG_SEARCH_NAME,

}

impl std::fmt::Display for ConfigSearch {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_SEARCH_NAME => write!(f, "name"),
        }
    }
}

impl Default for ConfigSearch {
    fn default() -> ConfigSearch {
        Self::CONFIG_SEARCH_NAME
    }
}

