/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContainerRepositoryType {
    #[serde(rename = "gar")]
    Gar,
    #[serde(rename = "dockerhub")]
    Dockerhub,
}

impl std::fmt::Display for ContainerRepositoryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Gar => write!(f, "gar"),
            Self::Dockerhub => write!(f, "dockerhub"),
        }
    }
}

impl Default for ContainerRepositoryType {
    fn default() -> ContainerRepositoryType {
        Self::Gar
    }
}
