/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerRepository {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "registry_url")]
    pub registry_url: String,
    #[serde(rename = "account_login")]
    pub account_login: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "uri")]
    pub uri: String,
    #[serde(rename = "type")]
    pub r#type: models::ContainerRepositoryType,
}

impl ContainerRepository {
    pub fn new(
        object: Object,
        id: String,
        registry_url: String,
        account_login: String,
        name: String,
        uri: String,
        r#type: models::ContainerRepositoryType,
    ) -> ContainerRepository {
        ContainerRepository {
            object,
            id,
            registry_url,
            account_login,
            name,
            uri,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "container_repository")]
    ContainerRepository,
}

impl Default for Object {
    fn default() -> Object {
        Self::ContainerRepository
    }
}
