/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTagTypeRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "schema")]
    pub schema: serde_json::Value,
}

impl CreateTagTypeRequest {
    pub fn new(name: String, schema: serde_json::Value) -> CreateTagTypeRequest {
        CreateTagTypeRequest { name, schema }
    }
}
