/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDeviceRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "hardware")]
    pub hardware: models::HardwareType,
}

impl CreateDeviceRequest {
    pub fn new(name: String, hardware: models::HardwareType) -> CreateDeviceRequest {
        CreateDeviceRequest {
            name,
            hardware,
        }
    }
}

