/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOverrideRequest {
    /// The config schema id
    #[serde(rename = "config_schema_id")]
    pub config_schema_id: String,
    /// The name of the override
    #[serde(rename = "name")]
    pub name: String,
    /// The hierarchy position of the override
    #[serde(rename = "hierarchy_position")]
    pub hierarchy_position: i32,
    /// The key value pairs to override
    #[serde(rename = "key_value_pairs")]
    pub key_value_pairs: Vec<models::KeyValuePair>,
}

impl CreateOverrideRequest {
    pub fn new(
        config_schema_id: String,
        name: String,
        hierarchy_position: i32,
        key_value_pairs: Vec<models::KeyValuePair>,
    ) -> CreateOverrideRequest {
        CreateOverrideRequest {
            config_schema_id,
            name,
            hierarchy_position,
            key_value_pairs,
        }
    }
}
