/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJobTemplateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "is_favorite")]
    pub is_favorite: bool,
    #[serde(rename = "scripts")]
    pub scripts: Vec<models::CreateScriptRequest>,
}

impl CreateJobTemplateRequest {
    pub fn new(
        name: String,
        is_favorite: bool,
        scripts: Vec<models::CreateScriptRequest>,
    ) -> CreateJobTemplateRequest {
        CreateJobTemplateRequest {
            name,
            is_favorite,
            scripts,
        }
    }
}
