/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreateDeploymentTargetStatus {
    #[serde(rename = "downloaded")]
    CREATE_DEPLOYMENT_TARGET_STATUS_DOWNLOADED,
    #[serde(rename = "active")]
    CREATE_DEPLOYMENT_TARGET_STATUS_ACTIVE,
}

impl std::fmt::Display for CreateDeploymentTargetStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CREATE_DEPLOYMENT_TARGET_STATUS_DOWNLOADED => write!(f, "downloaded"),
            Self::CREATE_DEPLOYMENT_TARGET_STATUS_ACTIVE => write!(f, "active"),
        }
    }
}

impl Default for CreateDeploymentTargetStatus {
    fn default() -> CreateDeploymentTargetStatus {
        Self::CREATE_DEPLOYMENT_TARGET_STATUS_DOWNLOADED
    }
}
