/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJobFromTemplateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "devices")]
    pub devices: Vec<String>,
}

impl CreateJobFromTemplateRequest {
    pub fn new(name: String, devices: Vec<String>) -> CreateJobFromTemplateRequest {
        CreateJobFromTemplateRequest { name, devices }
    }
}
