/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGitHubSourceArtifact {
    #[serde(rename = "allow_duplicate")]
    pub allow_duplicate: bool,
    #[serde(rename = "commit_sha")]
    pub commit_sha: String,
}

impl CreateGitHubSourceArtifact {
    pub fn new(allow_duplicate: bool, commit_sha: String) -> CreateGitHubSourceArtifact {
        CreateGitHubSourceArtifact {
            allow_duplicate,
            commit_sha,
        }
    }
}
