/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRegistrySourceArtifactImagesInner {
    #[serde(rename = "repository_id")]
    pub repository_id: String,
    #[serde(rename = "digest")]
    pub digest: String,
    #[serde(rename = "tag")]
    pub tag: String,
}

impl CreateRegistrySourceArtifactImagesInner {
    pub fn new(
        repository_id: String,
        digest: String,
        tag: String,
    ) -> CreateRegistrySourceArtifactImagesInner {
        CreateRegistrySourceArtifactImagesInner {
            repository_id,
            digest,
            tag,
        }
    }
}
