/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDeploymentsRequest {
    #[serde(rename = "artifact_ids")]
    pub artifact_ids: Vec<String>,
    #[serde(rename = "device_ids")]
    pub device_ids: Vec<String>,
    #[serde(rename = "target_status")]
    pub target_status: models::CreateDeploymentTargetStatus,
}

impl CreateDeploymentsRequest {
    pub fn new(
        artifact_ids: Vec<String>,
        device_ids: Vec<String>,
        target_status: models::CreateDeploymentTargetStatus,
    ) -> CreateDeploymentsRequest {
        CreateDeploymentsRequest {
            artifact_ids,
            device_ids,
            target_status,
        }
    }
}
