/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJobRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "scripts")]
    pub scripts: Vec<models::CreateScriptRequest>,
    #[serde(rename = "devices")]
    pub devices: Vec<String>,
}

impl CreateJobRequest {
    pub fn new(
        name: String,
        scripts: Vec<models::CreateScriptRequest>,
        devices: Vec<String>,
    ) -> CreateJobRequest {
        CreateJobRequest {
            name,
            scripts,
            devices,
        }
    }
}
