/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRegistrySourceArtifact {
    #[serde(rename = "allow_duplicate")]
    pub allow_duplicate: bool,
    #[serde(rename = "images")]
    pub images: Vec<models::CreateRegistrySourceArtifactImagesInner>,
}

impl CreateRegistrySourceArtifact {
    pub fn new(
        allow_duplicate: bool,
        images: Vec<models::CreateRegistrySourceArtifactImagesInner>,
    ) -> CreateRegistrySourceArtifact {
        CreateRegistrySourceArtifact {
            allow_duplicate,
            images,
        }
    }
}
