/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTagRequest {
    /// The tag type id
    #[serde(rename = "tag_type_id")]
    pub tag_type_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl CreateTagRequest {
    pub fn new(tag_type_id: String, name: String, metadata: serde_json::Value) -> CreateTagRequest {
        CreateTagRequest {
            tag_type_id,
            name,
            metadata,
        }
    }
}

