/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateScriptRequest {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "directory")]
    pub directory: String,
    #[serde(rename = "os_user_name")]
    pub os_user_name: String,
    #[serde(rename = "os_user_id")]
    pub os_user_id: String,
    #[serde(rename = "os_group_name")]
    pub os_group_name: String,
    #[serde(rename = "os_group_id")]
    pub os_group_id: String,
}

impl CreateScriptRequest {
    pub fn new(
        content: String,
        directory: String,
        os_user_name: String,
        os_user_id: String,
        os_group_name: String,
        os_group_id: String,
    ) -> CreateScriptRequest {
        CreateScriptRequest {
            content,
            directory,
            os_user_name,
            os_user_id,
            os_group_name,
            os_group_id,
        }
    }
}
