/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentLog {
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "level")]
    pub level: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "code")]
    pub code: String,
}

impl DeploymentLog {
    pub fn new(timestamp: String, level: String, message: String, code: String) -> DeploymentLog {
        DeploymentLog {
            timestamp,
            level,
            message,
            code,
        }
    }
}
