/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentErrorStatus {
    #[serde(rename = "none")]
    DEPLOYMENT_ERROR_STATUS_NONE,
    #[serde(rename = "retrying")]
    DEPLOYMENT_ERROR_STATUS_RETRYING,
    #[serde(rename = "failed")]
    DEPLOYMENT_ERROR_STATUS_FAILED,
}

impl std::fmt::Display for DeploymentErrorStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_ERROR_STATUS_NONE => write!(f, "none"),
            Self::DEPLOYMENT_ERROR_STATUS_RETRYING => write!(f, "retrying"),
            Self::DEPLOYMENT_ERROR_STATUS_FAILED => write!(f, "failed"),
        }
    }
}

impl Default for DeploymentErrorStatus {
    fn default() -> DeploymentErrorStatus {
        Self::DEPLOYMENT_ERROR_STATUS_NONE
    }
}
