/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentStatus {
    #[serde(rename = "queued")]
    DEPLOYMENT_STATUS_QUEUED,
    #[serde(rename = "downloading")]
    DEPLOYMENT_STATUS_DOWNLOADING,
    #[serde(rename = "downloaded")]
    DEPLOYMENT_STATUS_DOWNLOADED,
    #[serde(rename = "booting")]
    DEPLOYMENT_STATUS_BOOTING,
    #[serde(rename = "active")]
    DEPLOYMENT_STATUS_ACTIVE,
    #[serde(rename = "stopping")]
    DEPLOYMENT_STATUS_STOPPING,
    #[serde(rename = "stopped")]
    DEPLOYMENT_STATUS_STOPPED,
    #[serde(rename = "removing")]
    DEPLOYMENT_STATUS_REMOVING,
    #[serde(rename = "archived")]
    DEPLOYMENT_STATUS_ARCHIVED,
    #[serde(rename = "failed")]
    DEPLOYMENT_STATUS_FAILED,
    #[serde(rename = "retrying")]
    DEPLOYMENT_STATUS_RETRYING,

}

impl std::fmt::Display for DeploymentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_STATUS_QUEUED => write!(f, "queued"),
            Self::DEPLOYMENT_STATUS_DOWNLOADING => write!(f, "downloading"),
            Self::DEPLOYMENT_STATUS_DOWNLOADED => write!(f, "downloaded"),
            Self::DEPLOYMENT_STATUS_BOOTING => write!(f, "booting"),
            Self::DEPLOYMENT_STATUS_ACTIVE => write!(f, "active"),
            Self::DEPLOYMENT_STATUS_STOPPING => write!(f, "stopping"),
            Self::DEPLOYMENT_STATUS_STOPPED => write!(f, "stopped"),
            Self::DEPLOYMENT_STATUS_REMOVING => write!(f, "removing"),
            Self::DEPLOYMENT_STATUS_ARCHIVED => write!(f, "archived"),
            Self::DEPLOYMENT_STATUS_FAILED => write!(f, "failed"),
            Self::DEPLOYMENT_STATUS_RETRYING => write!(f, "retrying"),
        }
    }
}

impl Default for DeploymentStatus {
    fn default() -> DeploymentStatus {
        Self::DEPLOYMENT_STATUS_QUEUED
    }
}

