/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceStatus {
    #[serde(rename = "unauthenticated")]
    DEVICE_STATUS_UNAUTHENTICATED,
    #[serde(rename = "authenticated")]
    DEVICE_STATUS_AUTHENTICATED,
    #[serde(rename = "idle")]
    DEVICE_STATUS_IDLE,
    #[serde(rename = "running")]
    DEVICE_STATUS_RUNNING,
    #[serde(rename = "offline")]
    DEVICE_STATUS_OFFLINE,
    #[serde(rename = "updating")]
    DEVICE_STATUS_UPDATING,
    #[serde(rename = "error")]
    DEVICE_STATUS_ERROR,

}

impl std::fmt::Display for DeviceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEVICE_STATUS_UNAUTHENTICATED => write!(f, "unauthenticated"),
            Self::DEVICE_STATUS_AUTHENTICATED => write!(f, "authenticated"),
            Self::DEVICE_STATUS_IDLE => write!(f, "idle"),
            Self::DEVICE_STATUS_RUNNING => write!(f, "running"),
            Self::DEVICE_STATUS_OFFLINE => write!(f, "offline"),
            Self::DEVICE_STATUS_UPDATING => write!(f, "updating"),
            Self::DEVICE_STATUS_ERROR => write!(f, "error"),
        }
    }
}

impl Default for DeviceStatus {
    fn default() -> DeviceStatus {
        Self::DEVICE_STATUS_UNAUTHENTICATED
    }
}

