/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DockerBuildLog {
    #[serde(rename = "service_name")]
    pub service_name: String,
    #[serde(rename = "build_steps")]
    pub build_steps: Vec<models::BuildStep>,
}

impl DockerBuildLog {
    pub fn new(service_name: String, build_steps: Vec<models::BuildStep>) -> DockerBuildLog {
        DockerBuildLog {
            service_name,
            build_steps,
        }
    }
}

