/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadDeploymentsRequest {
    #[serde(rename = "deployment_ids")]
    pub deployment_ids: Vec<String>,
}

impl DownloadDeploymentsRequest {
    pub fn new(deployment_ids: Vec<String>) -> DownloadDeploymentsRequest {
        DownloadDeploymentsRequest {
            deployment_ids,
        }
    }
}

