/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DuplicateArtifactErrorParams {
    #[serde(rename = "duplicate_artifacts")]
    pub duplicate_artifacts: Vec<serde_json::Value>,
}

impl DuplicateArtifactErrorParams {
    pub fn new(duplicate_artifacts: Vec<serde_json::Value>) -> DuplicateArtifactErrorParams {
        DuplicateArtifactErrorParams {
            duplicate_artifacts,
        }
    }
}
