/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DuplicateArtifactError {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "params")]
    pub params: Box<models::DuplicateArtifactErrorParams>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "debug_message", skip_serializing_if = "Option::is_none")]
    pub debug_message: Option<String>,
}

impl DuplicateArtifactError {
    pub fn new(
        code: String,
        params: models::DuplicateArtifactErrorParams,
        message: String,
    ) -> DuplicateArtifactError {
        DuplicateArtifactError {
            code,
            params: Box::new(params),
            message,
            debug_message: None,
        }
    }
}
