/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubSourceDataRepository {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "clone_url")]
    pub clone_url: String,
    #[serde(rename = "full_name")]
    pub full_name: String,
    #[serde(rename = "pushed_at")]
    pub pushed_at: String,
}

impl GitHubSourceDataRepository {
    pub fn new(id: i64, html_url: String, clone_url: String, full_name: String, pushed_at: String) -> GitHubSourceDataRepository {
        GitHubSourceDataRepository {
            id,
            html_url,
            clone_url,
            full_name,
            pushed_at,
        }
    }
}

