/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubCommitter {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "login")]
    pub login: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
}

impl GitHubCommitter {
    pub fn new(
        id: i64,
        object: Object,
        login: String,
        r#type: String,
        html_url: String,
        avatar_url: String,
    ) -> GitHubCommitter {
        GitHubCommitter {
            id,
            object,
            login,
            r#type,
            html_url,
            avatar_url,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "github_committer")]
    GithubCommitter,
}

impl Default for Object {
    fn default() -> Object {
        Self::GithubCommitter
    }
}
