/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubSourceDataHeadCommit {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl GitHubSourceDataHeadCommit {
    pub fn new(id: String, url: String, message: String) -> GitHubSourceDataHeadCommit {
        GitHubSourceDataHeadCommit { id, url, message }
    }
}
