/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubSourceDataSender {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "login")]
    pub login: String,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
}

impl GitHubSourceDataSender {
    pub fn new(
        id: i64,
        r#type: String,
        login: String,
        html_url: String,
        avatar_url: String,
    ) -> GitHubSourceDataSender {
        GitHubSourceDataSender {
            id,
            r#type,
            login,
            html_url,
            avatar_url,
        }
    }
}
