/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GitCommitOrderBy {
    #[serde(rename = "id")]
    GIT_COMMIT_ORDER_BY_ID,
    #[serde(rename = "created_at")]
    GIT_COMMIT_ORDER_BY_CREATED_AT,
    #[serde(rename = "commit_sha")]
    GIT_COMMIT_ORDER_BY_COMMIT_SHA,
    #[serde(rename = "branch")]
    GIT_COMMIT_ORDER_BY_BRANCH,
    #[serde(rename = "repository_name")]
    GIT_COMMIT_ORDER_BY_REPOSITORY_NAME,
}

impl std::fmt::Display for GitCommitOrderBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GIT_COMMIT_ORDER_BY_ID => write!(f, "id"),
            Self::GIT_COMMIT_ORDER_BY_CREATED_AT => write!(f, "created_at"),
            Self::GIT_COMMIT_ORDER_BY_COMMIT_SHA => write!(f, "commit_sha"),
            Self::GIT_COMMIT_ORDER_BY_BRANCH => write!(f, "branch"),
            Self::GIT_COMMIT_ORDER_BY_REPOSITORY_NAME => write!(f, "repository_name"),
        }
    }
}

impl Default for GitCommitOrderBy {
    fn default() -> GitCommitOrderBy {
        Self::GIT_COMMIT_ORDER_BY_ID
    }
}
