/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashSchemaSerializedRequest {
    #[serde(rename = "format")]
    pub format: models::HashSerializedConfigSchemaFormat,
    #[serde(rename = "schema")]
    pub schema: String,
}

impl HashSchemaSerializedRequest {
    pub fn new(
        format: models::HashSerializedConfigSchemaFormat,
        schema: String,
    ) -> HashSchemaSerializedRequest {
        HashSchemaSerializedRequest { format, schema }
    }
}
