/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueClientTokenRequest {
    #[serde(rename = "claims")]
    pub claims: Box<models::IssueClientClaims>,
    /// The signature
    #[serde(rename = "signature")]
    pub signature: String,
}

impl IssueClientTokenRequest {
    pub fn new(claims: models::IssueClientClaims, signature: String) -> IssueClientTokenRequest {
        IssueClientTokenRequest {
            claims: Box::new(claims),
            signature,
        }
    }
}

