/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueDeviceClaims {
    /// The device ID
    #[serde(rename = "device_id")]
    pub device_id: String,
    /// The nonce
    #[serde(rename = "nonce")]
    pub nonce: String,
    /// The expiration
    #[serde(rename = "expiration")]
    pub expiration: String,
}

impl IssueDeviceClaims {
    pub fn new(device_id: String, nonce: String, expiration: String) -> IssueDeviceClaims {
        IssueDeviceClaims {
            device_id,
            nonce,
            expiration,
        }
    }
}

