/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Job {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: models::JobPurpose,
    #[serde(rename = "job_template_id", deserialize_with = "Option::deserialize")]
    pub job_template_id: Option<String>,
    #[serde(rename = "runs")]
    pub runs: Box<models::JobRunList>,
    #[serde(rename = "created_by", deserialize_with = "Option::deserialize")]
    pub created_by: Option<Box<models::User>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "workspace_id")]
    pub workspace_id: String,
    #[serde(rename = "scripts")]
    pub scripts: Box<models::ScriptList>,
}

impl Job {
    pub fn new(object: Object, id: String, name: String, r#type: models::JobPurpose, job_template_id: Option<String>, runs: models::JobRunList, created_by: Option<models::User>, created_at: String, workspace_id: String, scripts: models::ScriptList) -> Job {
        Job {
            object,
            id,
            name,
            r#type,
            job_template_id,
            runs: Box::new(runs),
            created_by: if let Some(x) = created_by {Some(Box::new(x))} else {None},
            created_at,
            workspace_id,
            scripts: Box::new(scripts),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "job")]
    Job,
}

impl Default for Object {
    fn default() -> Object {
        Self::Job
    }
}

