/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobRunStatus {
    #[serde(rename = "queued")]
    JOB_RUN_STATUS_QUEUED,
    #[serde(rename = "downloading")]
    JOB_RUN_STATUS_DOWNLOADING,
    #[serde(rename = "downloaded")]
    JOB_RUN_STATUS_DOWNLOADED,
    #[serde(rename = "running")]
    JOB_RUN_STATUS_RUNNING,
    #[serde(rename = "ran")]
    JOB_RUN_STATUS_RAN,
    #[serde(rename = "uploading")]
    JOB_RUN_STATUS_UPLOADING,
    #[serde(rename = "uploaded")]
    JOB_RUN_STATUS_UPLOADED,
    #[serde(rename = "removing")]
    JOB_RUN_STATUS_REMOVING,
    #[serde(rename = "archived")]
    JOB_RUN_STATUS_ARCHIVED,
    #[serde(rename = "failed")]
    JOB_RUN_STATUS_FAILED,
    #[serde(rename = "retrying")]
    JOB_RUN_STATUS_RETRYING,
}

impl std::fmt::Display for JobRunStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::JOB_RUN_STATUS_QUEUED => write!(f, "queued"),
            Self::JOB_RUN_STATUS_DOWNLOADING => write!(f, "downloading"),
            Self::JOB_RUN_STATUS_DOWNLOADED => write!(f, "downloaded"),
            Self::JOB_RUN_STATUS_RUNNING => write!(f, "running"),
            Self::JOB_RUN_STATUS_RAN => write!(f, "ran"),
            Self::JOB_RUN_STATUS_UPLOADING => write!(f, "uploading"),
            Self::JOB_RUN_STATUS_UPLOADED => write!(f, "uploaded"),
            Self::JOB_RUN_STATUS_REMOVING => write!(f, "removing"),
            Self::JOB_RUN_STATUS_ARCHIVED => write!(f, "archived"),
            Self::JOB_RUN_STATUS_FAILED => write!(f, "failed"),
            Self::JOB_RUN_STATUS_RETRYING => write!(f, "retrying"),
        }
    }
}

impl Default for JobRunStatus {
    fn default() -> JobRunStatus {
        Self::JOB_RUN_STATUS_QUEUED
    }
}
