/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobRunErrorStatus {
    #[serde(rename = "none")]
    JOB_RUN_ERROR_STATUS_NONE,
    #[serde(rename = "failed")]
    JOB_RUN_ERROR_STATUS_FAILED,
    #[serde(rename = "retrying")]
    JOB_RUN_ERROR_STATUS_RETRYING,

}

impl std::fmt::Display for JobRunErrorStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::JOB_RUN_ERROR_STATUS_NONE => write!(f, "none"),
            Self::JOB_RUN_ERROR_STATUS_FAILED => write!(f, "failed"),
            Self::JOB_RUN_ERROR_STATUS_RETRYING => write!(f, "retrying"),
        }
    }
}

impl Default for JobRunErrorStatus {
    fn default() -> JobRunErrorStatus {
        Self::JOB_RUN_ERROR_STATUS_NONE
    }
}

