/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Jwt {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "jwt")]
    pub jwt: String,
}

impl Jwt {
    pub fn new(object: Object, jwt: String) -> Jwt {
        Jwt { object, jwt }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "jwt")]
    Jwt,
}

impl Default for Object {
    fn default() -> Object {
        Self::Jwt
    }
}
