/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogEntry {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "level")]
    pub level: models::LogLevel,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl LogEntry {
    pub fn new(
        object: Object,
        level: models::LogLevel,
        timestamp: String,
        message: String,
    ) -> LogEntry {
        LogEntry {
            object,
            level,
            timestamp,
            message,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "log_entry")]
    LogEntry,
}

impl Default for Object {
    fn default() -> Object {
        Self::LogEntry
    }
}
