/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OverrideSearch {
    #[serde(rename = "name")]
    OVERRIDE_SEARCH_NAME,
    #[serde(rename = "config_schema")]
    OVERRIDE_SEARCH_CONFIG_SCHEMA,
}

impl std::fmt::Display for OverrideSearch {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OVERRIDE_SEARCH_NAME => write!(f, "name"),
            Self::OVERRIDE_SEARCH_CONFIG_SCHEMA => write!(f, "config_schema"),
        }
    }
}

impl Default for OverrideSearch {
    fn default() -> OverrideSearch {
        Self::OVERRIDE_SEARCH_NAME
    }
}
