/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OverrideExpand {
    #[serde(rename = "created_by")]
    OVERRIDE_EXPAND_CREATED_BY,
    #[serde(rename = "updated_by")]
    OVERRIDE_EXPAND_UPDATED_BY,
    #[serde(rename = "key_value_pairs")]
    OVERRIDE_EXPAND_KEY_VALUE_PAIRS,
    #[serde(rename = "config_schema")]
    OVERRIDE_EXPAND_CONFIG_SCHEMA,

}

impl std::fmt::Display for OverrideExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OVERRIDE_EXPAND_CREATED_BY => write!(f, "created_by"),
            Self::OVERRIDE_EXPAND_UPDATED_BY => write!(f, "updated_by"),
            Self::OVERRIDE_EXPAND_KEY_VALUE_PAIRS => write!(f, "key_value_pairs"),
            Self::OVERRIDE_EXPAND_CONFIG_SCHEMA => write!(f, "config_schema"),
        }
    }
}

impl Default for OverrideExpand {
    fn default() -> OverrideExpand {
        Self::OVERRIDE_EXPAND_CREATED_BY
    }
}

