/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshLatestConcreteConfigRequest {
    /// The client id
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// The config schema digest
    #[serde(rename = "config_schema_digest")]
    pub config_schema_digest: String,
    /// The config slug
    #[serde(rename = "config_slug")]
    pub config_slug: String,
}

impl RefreshLatestConcreteConfigRequest {
    pub fn new(client_id: String, config_schema_digest: String, config_slug: String) -> RefreshLatestConcreteConfigRequest {
        RefreshLatestConcreteConfigRequest {
            client_id,
            config_schema_digest,
            config_slug,
        }
    }
}

