/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenderConfigSchemaRequest {
    /// The client id
    #[serde(rename = "client_id", deserialize_with = "Option::deserialize")]
    pub client_id: Option<String>,
    /// The tag ids
    #[serde(rename = "tag_ids")]
    pub tag_ids: Vec<String>,
}

impl RenderConfigSchemaRequest {
    pub fn new(client_id: Option<String>, tag_ids: Vec<String>) -> RenderConfigSchemaRequest {
        RenderConfigSchemaRequest { client_id, tag_ids }
    }
}
