/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenderWalkStep {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "key_value_pair")]
    pub key_value_pair: Box<models::RenderedKeyValuePair>,
    #[serde(rename = "overwrote_previous")]
    pub overwrote_previous: bool,
    #[serde(
        rename = "overwrite_explanation",
        skip_serializing_if = "Option::is_none"
    )]
    pub overwrite_explanation: Option<String>,
}

impl RenderWalkStep {
    pub fn new(
        object: Object,
        key_value_pair: models::RenderedKeyValuePair,
        overwrote_previous: bool,
    ) -> RenderWalkStep {
        RenderWalkStep {
            object,
            key_value_pair: Box::new(key_value_pair),
            overwrote_previous,
            overwrite_explanation: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "render_walk_step")]
    RenderWalkStep,
}

impl Default for Object {
    fn default() -> Object {
        Self::RenderWalkStep
    }
}
