/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RenderedConfigSchemaExpand {
    #[serde(rename = "config_schema")]
    RENDERED_CONFIG_SCHEMA_EXPAND_CONFIG_SCHEMA,
    #[serde(rename = "rendered_key_value_pairs")]
    RENDERED_CONFIG_SCHEMA_EXPAND_RENDERED_KEY_VALUE_PAIRS,
    #[serde(rename = "rendered_overrides")]
    RENDERED_CONFIG_SCHEMA_EXPAND_RENDERED_OVERRIDES,

}

impl std::fmt::Display for RenderedConfigSchemaExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RENDERED_CONFIG_SCHEMA_EXPAND_CONFIG_SCHEMA => write!(f, "config_schema"),
            Self::RENDERED_CONFIG_SCHEMA_EXPAND_RENDERED_KEY_VALUE_PAIRS => write!(f, "rendered_key_value_pairs"),
            Self::RENDERED_CONFIG_SCHEMA_EXPAND_RENDERED_OVERRIDES => write!(f, "rendered_overrides"),
        }
    }
}

impl Default for RenderedConfigSchemaExpand {
    fn default() -> RenderedConfigSchemaExpand {
        Self::RENDERED_CONFIG_SCHEMA_EXPAND_CONFIG_SCHEMA
    }
}

