/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RenderedOverrideExpand {
    #[serde(rename = "override")]
    RENDERED_OVERRIDE_EXPAND_OVERRIDE,
    #[serde(rename = "rendered_key_value_pairs")]
    RENDERED_OVERRIDE_EXPAND_RENDERED_KEY_VALUE_PAIRS,

}

impl std::fmt::Display for RenderedOverrideExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RENDERED_OVERRIDE_EXPAND_OVERRIDE => write!(f, "override"),
            Self::RENDERED_OVERRIDE_EXPAND_RENDERED_KEY_VALUE_PAIRS => write!(f, "rendered_key_value_pairs"),
        }
    }
}

impl Default for RenderedOverrideExpand {
    fn default() -> RenderedOverrideExpand {
        Self::RENDERED_OVERRIDE_EXPAND_OVERRIDE
    }
}

