/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryNotFoundParams {
    #[serde(rename = "registry_type")]
    pub registry_type: String,
    #[serde(rename = "registry_url")]
    pub registry_url: String,
    #[serde(rename = "repository_name")]
    pub repository_name: String,
    #[serde(rename = "uri")]
    pub uri: String,
}

impl RepositoryNotFoundParams {
    pub fn new(
        registry_type: String,
        registry_url: String,
        repository_name: String,
        uri: String,
    ) -> RepositoryNotFoundParams {
        RepositoryNotFoundParams {
            registry_type,
            registry_url,
            repository_name,
            uri,
        }
    }
}
