/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScriptType {
    #[serde(rename = "sh")]
    Sh,
    #[serde(rename = "bash")]
    Bash,
}

impl std::fmt::Display for ScriptType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sh => write!(f, "sh"),
            Self::Bash => write!(f, "bash"),
        }
    }
}

impl Default for ScriptType {
    fn default() -> ScriptType {
        Self::Sh
    }
}
