/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StopDeploymentsRequest {
    #[serde(rename = "deployment_ids")]
    pub deployment_ids: Vec<String>,
}

impl StopDeploymentsRequest {
    pub fn new(deployment_ids: Vec<String>) -> StopDeploymentsRequest {
        StopDeploymentsRequest { deployment_ids }
    }
}
