/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TagExpand {
    #[serde(rename = "created_by")]
    TAG_EXPAND_CREATED_BY,
    #[serde(rename = "updated_by")]
    TAG_EXPAND_UPDATED_BY,
    #[serde(rename = "tag_type")]
    TAG_EXPAND_TAG_TYPE,
    #[serde(rename = "metadata")]
    TAG_EXPAND_METADATA,
}

impl std::fmt::Display for TagExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TAG_EXPAND_CREATED_BY => write!(f, "created_by"),
            Self::TAG_EXPAND_UPDATED_BY => write!(f, "updated_by"),
            Self::TAG_EXPAND_TAG_TYPE => write!(f, "tag_type"),
            Self::TAG_EXPAND_METADATA => write!(f, "metadata"),
        }
    }
}

impl Default for TagExpand {
    fn default() -> TagExpand {
        Self::TAG_EXPAND_CREATED_BY
    }
}
