/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TagOrderBy {
    #[serde(rename = "id")]
    TAG_ORDER_BY_ID,
    #[serde(rename = "created_at")]
    TAG_ORDER_BY_CREATED_AT,
    #[serde(rename = "updated_at")]
    TAG_ORDER_BY_UPDATED_AT,
    #[serde(rename = "name")]
    TAG_ORDER_BY_NAME,
}

impl std::fmt::Display for TagOrderBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TAG_ORDER_BY_ID => write!(f, "id"),
            Self::TAG_ORDER_BY_CREATED_AT => write!(f, "created_at"),
            Self::TAG_ORDER_BY_UPDATED_AT => write!(f, "updated_at"),
            Self::TAG_ORDER_BY_NAME => write!(f, "name"),
        }
    }
}

impl Default for TagOrderBy {
    fn default() -> TagOrderBy {
        Self::TAG_ORDER_BY_ID
    }
}
