/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TagTypeSearch {
    #[serde(rename = "name")]
    TAG_TYPE_SEARCH_NAME,
}

impl std::fmt::Display for TagTypeSearch {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TAG_TYPE_SEARCH_NAME => write!(f, "name"),
        }
    }
}

impl Default for TagTypeSearch {
    fn default() -> TagTypeSearch {
        Self::TAG_TYPE_SEARCH_NAME
    }
}
