/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TagTypeExpand {
    #[serde(rename = "created_by")]
    TAG_TYPE_EXPAND_CREATED_BY,
    #[serde(rename = "updated_by")]
    TAG_TYPE_EXPAND_UPDATED_BY,
    #[serde(rename = "schema")]
    TAG_TYPE_EXPAND_SCHEMA,
    #[serde(rename = "tags")]
    TAG_TYPE_EXPAND_TAGS,
}

impl std::fmt::Display for TagTypeExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TAG_TYPE_EXPAND_CREATED_BY => write!(f, "created_by"),
            Self::TAG_TYPE_EXPAND_UPDATED_BY => write!(f, "updated_by"),
            Self::TAG_TYPE_EXPAND_SCHEMA => write!(f, "schema"),
            Self::TAG_TYPE_EXPAND_TAGS => write!(f, "tags"),
        }
    }
}

impl Default for TagTypeExpand {
    fn default() -> TagTypeExpand {
        Self::TAG_TYPE_EXPAND_CREATED_BY
    }
}
