/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTagRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl UpdateTagRequest {
    pub fn new(name: String, metadata: serde_json::Value) -> UpdateTagRequest {
        UpdateTagRequest { name, metadata }
    }
}
