/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRegistrySourceRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "compose_file")]
    pub compose_file: String,
    #[serde(rename = "extra_repositories")]
    pub extra_repositories: Vec<String>,
    #[serde(rename = "aarch64")]
    pub aarch64: bool,
    #[serde(rename = "x86_64")]
    pub x86_64: bool,
}

impl UpdateRegistrySourceRequest {
    pub fn new(
        name: String,
        compose_file: String,
        extra_repositories: Vec<String>,
        aarch64: bool,
        x86_64: bool,
    ) -> UpdateRegistrySourceRequest {
        UpdateRegistrySourceRequest {
            name,
            compose_file,
            extra_repositories,
            aarch64,
            x86_64,
        }
    }
}
