/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOverrideHierarchyRequest {
    /// The override ids
    #[serde(rename = "override_ids")]
    pub override_ids: Vec<String>,
}

impl UpdateOverrideHierarchyRequest {
    pub fn new(override_ids: Vec<String>) -> UpdateOverrideHierarchyRequest {
        UpdateOverrideHierarchyRequest {
            override_ids,
        }
    }
}

