/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWorkspaceRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "billing_plan")]
    pub billing_plan: models::BillingPlan,
}

impl UpdateWorkspaceRequest {
    pub fn new(name: String, billing_plan: models::BillingPlan) -> UpdateWorkspaceRequest {
        UpdateWorkspaceRequest { name, billing_plan }
    }
}
