/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserRequest {
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(rename = "last_name")]
    pub last_name: String,
    #[serde(rename = "onboarded")]
    pub onboarded: bool,
}

impl UpdateUserRequest {
    pub fn new(first_name: String, last_name: String, onboarded: bool) -> UpdateUserRequest {
        UpdateUserRequest {
            first_name,
            last_name,
            onboarded,
        }
    }
}
