/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTagTypeRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "can_set_override_key_value_pairs_null")]
    pub can_set_override_key_value_pairs_null: bool,
    #[serde(rename = "can_delete_tag_metadata")]
    pub can_delete_tag_metadata: bool,
    #[serde(rename = "schema")]
    pub schema: serde_json::Value,
    #[serde(rename = "dry_run")]
    pub dry_run: bool,
}

impl UpdateTagTypeRequest {
    pub fn new(
        name: String,
        can_set_override_key_value_pairs_null: bool,
        can_delete_tag_metadata: bool,
        schema: serde_json::Value,
        dry_run: bool,
    ) -> UpdateTagTypeRequest {
        UpdateTagTypeRequest {
            name,
            can_set_override_key_value_pairs_null,
            can_delete_tag_metadata,
            schema,
            dry_run,
        }
    }
}
