/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserExpand {
    #[serde(rename = "workspace")]
    USER_EXPAND_WORKSPACE,
}

impl std::fmt::Display for UserExpand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::USER_EXPAND_WORKSPACE => write!(f, "workspace"),
        }
    }
}

impl Default for UserExpand {
    fn default() -> UserExpand {
        Self::USER_EXPAND_WORKSPACE
    }
}
